import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Footer from "@/components/footer"
import Header from "@/components/header"
import Main from "@/components/main"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="[--header-height:calc(--spacing(14))]">
          <Header />
          <SidebarProvider
            className="flex flex-col"
            style={
              {
                "--sidebar-width": "10rem",
              } as React.CSSProperties
            }
          >
            <div className="flex flex-1">
              <AppSidebar />
              <SidebarInset>
                <Main>
                  <main>{children}</main>
                </Main>
              </SidebarInset>
            </div>
          </SidebarProvider>
          <Footer />
        </div>
      </body>
    </html>
  )
}
